// Stub module. Real file is generated by `npx convex dev`.
// This exists so Vite/Rollup can resolve dynamic imports before Convex codegen runs.
// All actual API calls are wrapped in try/catch, so this being a stub is safe.
export const api = new Proxy({}, {
  get(_, table) {
    return new Proxy({}, {
      get(_, method) {
        return `${String(table)}:${String(method)}`
      }
    })
  }
})
