/// <reference types="vite/client" />

// Stub for Convex generated API (auto-generated by `npx convex dev`)
declare module "../../convex/_generated/api" {
  import type { FunctionReference } from "convex/server"
  export const api: {
    sandboxes: {
      getByUser: FunctionReference<"query", "public">
    }
    ralphs: {
      getByUser: FunctionReference<"query", "public">
      getBySandbox: FunctionReference<"query", "public">
    }
    agentEvents: {
      getByRalph: FunctionReference<"query", "public">
    }
    users: {
      me: FunctionReference<"query", "public">
      upsertFromClerk: FunctionReference<"mutation", "public">
    }
  }
}
